### ISSUE TITLE
[FEAT] 유저 조회 서버 구현

### ISSUE THREAD

**Issue by jinsilWoo** [SOPT-Joint-Seminar-Twitter/Twitter-AOS#16]
## 🐥 Issue
유저 조회 서버 구현하기 

## 📝 To-do
- [x] 유저 조회 Response,Request 작성
- [x] HomeActivity 서버 연결 
- [x] 서버 연결 확인
