### ISSUE TITLE
[FEAT] 글쓰기 기능 구현

### ISSUE THREAD

**Issue by KWY0218** [SOPT-Joint-Seminar-Twitter/Twitter-AOS#3]
## 🐥 Issue
글쓰기 기능 구현

## 📝 To-do
- [x]  String 추가
- [x]  UI Widget
    - Button * 2
    - ImageView, EditText
    - ImageView, RecyclerView (Linear layout, Horizontal)
    - Divider
    - ImageView, TextView
    - Divider
    - ImageView * 4 , ImageView , Divider, ImageView
- [x]  EditText Cusor Color 변경
- [x]  RecyclerView Item Frame 구현
- [x]  RecyclerView 구현 + item 넣기
- [x]  Edit Text Empty 여부에 따른 `트윗` 버튼 색 변경
- [x]  키보드와 위젯 묶기
- [x]  글쓰기 화면 들어오자마자 키보드 올라오게 만들기
